name: mil
description: A new Flutter project for mil

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  google_fonts: ^2.3.2
  dropdown_button2: ^1.2.2
  share: ^2.0.4
  flutter:
    sdk: flutter
  restart_app: ^1.1.0
  grouped_list: ^5.1.2
  google_maps_flutter: ^2.2.2
  geolocator: ^9.0.2
  image_picker: ^0.8.7


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  quickalert: ^1.0.1
  intl: ^0.18.0
  flutter_riverpod: ^0.14.0+1
  provider: ^6.0.2
  http: ^0.13.4
  webview_flutter: ^2.0.13
  shared_preferences: ^2.0.13
  pie_chart: ^5.3.0
  flutterfire_cli: ^0.2.4
  firebase_crashlytics: ^3.0.3
  firebase_analytics: ^10.0.3
  firebase_core: ^2.1.1
  permission_handler: ^10.2.0
  share_extend: ^2.0.0
  fluttertoast: ^8.1.2
  email_validator: ^2.0.1
  field_validation: ^0.0.1
#  flutter_launcher_icons: ^0.11.0

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

  #  fonts:
  #    - family: Nuosu SIL
  #      fonts:
  #        - asset: Fonts/NuosuSIL-Regular.ttf

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/app_icon/
    - assets/google_fonts/
    - assets/images/
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 600